### ISSUE TITLE
Failed to activate the javascript-drag-import package

### ISSUE THREAD

**Issue by Mattes0h** [ElecTreeFrying/javascript-drag-import#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [javascript-drag-import](https://github.com/ElecTreeFrying/javascript-drag-import) package 0.1.2

### Stack Trace

Failed to activate the javascript-drag-import package

```
At Cannot read property 'addEventListener' of null

TypeError: Cannot read property 'addEventListener' of null
    at /packages/javascript-drag-import/lib/main.js:144:19
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:428320)
    at Object.activate (/packages/javascript-drag-import/lib/main.js:135:43)
    at Package.activateNow (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3319936)
    at measure (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3319348)
    at Package.measure (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3316958)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3319208)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3319151)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:382452)
    at ~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:941081
    at r (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:935687)
    at n (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1124813)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1125019)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.17 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
hey-pane 1.2.0 
Hydrogen 2.14.0 
javascript-drag-import 0.1.2 
scroll-through-time 0.3.1 
teletype 0.13.4 
zentabs 0.8.9 
```

**Comment by ElecTreeFrying** [comment]
I can't reproduce the error. Have you tried reloading (`ctrl+shift+F5`) ?

**Comment by ElecTreeFrying** [comment]
Hi, I replaced `querySelector` with an atom api. This should work.

**Comment by ElecTreeFrying** [comment]
Feel free to drop any message here if something went wrong. 😊
